{% set name = "notebook-frontend" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8b6100178eec79f765274385e81543c474c3ae11f097aa86b9bfcaecbfcb6fa9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - jupyterlab-js =4.5.0

test:
  imports:
    - notebook_frontend
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/notebook-frontend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package distributing Notebook's static assets
  dev_url: https://github.com/davidbrochart/notebook-frontend

extra:
  recipe-maintainers:
    - davidbrochart
